import { 
  Pencil, 
  Eraser, 
  PaintBucket, 
  Play, 
  Pause, 
  Plus, 
  Trash2, 
  Copy, 
  Settings, 
  Undo, 
  Redo, 
  Layers, 
  ChevronLeft, 
  Download, 
  Eye, 
  EyeOff, 
  Lock, 
  Unlock, 
  Music, 
  X, 
  Volume2, 
  Ghost, 
  Maximize2, 
  Minimize2, 
  MousePointer2, 
  Image,
  FlipHorizontal, 
  FlipVertical, 
  RotateCw, 
  RotateCcw,
  Repeat,
  Grid3X3, 
  Square, 
  Circle, 
  Minus, 
  Clipboard, 
  Home, 
  Save,
  Type,
  FileVideo,
  FileImage,
  FileArchive,
  Loader2,
  Upload,
  FolderDown,
  FileJson,
  HelpCircle,
  Palette,
  Highlighter,
  PenTool,
  SprayCan,
  Grid2X2,
  Monitor,
  LayoutGrid,
  Check,
  Mic,
  GripVertical,
  Wand2,
  Share2,
  Folder,
  FolderPlus,
  FolderOpen,
  FolderOutput,
  Film,
  Clapperboard,
  MoreVertical,
  Edit2,
  Brush,
  Video,
  Triangle,
  Star,
  Hexagon,
  Heart,
  ArrowRight,
  MessageCircle,
  Briefcase,
  ZoomIn,
  ZoomOut,
  Smartphone,
  Lasso,
  Pipette,
  Scissors,
  Search,
  Camera,
  Bold,
  Italic,
  SkipBack,
  SkipForward,
  ArrowUpDown,
  ArrowUp,
  ArrowDown,
  Sun,
  Moon,
  Laptop,
  Box,
  Gamepad2,
  Code,
  Clock,
  BookOpen,
  Sparkles,
  Lightbulb,
  GraduationCap,
  Compass,
  ChevronRight,
  Library,
  Wind,
  Zap,
  VolumeX,
  Gamepad,
  Filter,
  SlidersHorizontal,
  Tag,
  Info,
  ExternalLink,
  Radio,
  Disc,
  Activity,
  ChevronDown,
  List,
  FolderInput,
  FastForward,
  Shuffle,
  Split,
  Package,
  Flame,
  Coins,
  PlayCircle,
  PauseCircle,
  RefreshCw,
  ImagePlus,
  CheckSquare,
  Crop,
  Edit3
} from 'lucide-react';

const HalfCircle = ({ size = 20, className = '' }: { size?: number; className?: string }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
    <path d="M3 16 A 9 9 0 0 1 21 16 Z" />
  </svg>
);

const Diamond = ({ size = 20, className = '' }: { size?: number; className?: string }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
    <polygon points="12 3 21 12 12 21 3 12" />
  </svg>
);

const Pentagon = ({ size = 20, className = '' }: { size?: number; className?: string }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
    <polygon points="12 3 21 9 18 20 6 20 3 9" />
  </svg>
);

const Octagon = ({ size = 20, className = '' }: { size?: number; className?: string }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
    <polygon points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86" />
  </svg>
);

const Cross = ({ size = 20, className = '' }: { size?: number; className?: string }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
    <path d="M8 3 H16 V8 H21 V16 H16 V21 H8 V16 H3 V8 H8 Z" />
  </svg>
);

const Trapezoid = ({ size = 20, className = '' }: { size?: number; className?: string }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
    <polygon points="7 5 17 5 21 19 3 19" />
  </svg>
);

const CloudShape = ({ size = 20, className = '' }: { size?: number; className?: string }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
    <path d="M17.5 19C19.9853 19 22 16.9853 22 14.5C22 12.151 20.198 10.2229 17.8985 10.0242C17.433 6.58804 14.4844 4 11 4C7.80806 4 5.12781 6.18342 4.31682 9.17647C2.41727 9.87327 1 11.7001 1 14C1 16.7614 3.23858 19 6 19H17.5Z" />
  </svg>
);

const Ring = ({ size = 20, className = '' }: { size?: number; className?: string }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
    <circle cx="12" cy="12" r="9" />
    <circle cx="12" cy="12" r="4" />
  </svg>
);

export const Icons = {
  HalfCircle,
  Diamond,
  Pentagon,
  Octagon,
  Cross,
  Trapezoid,
  CloudShape,
  Ring,
  Pencil,
  Eraser,
  PaintBucket,
  Eyedropper: Pipette,
  Play, 
  Pause, 
  Plus, 
  Trash2, 
  Copy, 
  Settings, 
  Undo, 
  Redo,
  Layers,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Download,
  Eye, 
  EyeOff, 
  Lock, 
  Unlock, 
  List,
  FolderInput,
  FastForward,
  Shuffle,
  Split, 
  Music, 
  X, 
  Volume2, 
  VolumeX,
  Gamepad, 
  Ghost, 
  Maximize2, 
  Minimize2, 
  MousePointer2, 
  Image,
  FlipHorizontal, 
  FlipVertical, 
  RotateCw, 
  RotateCcw,
  Repeat,
  Grid: Grid3X3,
  Square, 
  Circle, 
  Minus,
  Line: Minus,
  SkipBack,
  SkipForward,
  Triangle,
  Star,
  Hexagon,
  Heart,
  ArrowRight,
  MessageCircle,
  Clipboard, 
  Home, 
  Save,
  Type,
  FileVideo,
  FileImage,
  FileArchive,
  Loader2,
  Upload,
  FolderDown,
  FileJson,
  Help: HelpCircle,
  Palette,
  Highlighter,
  Marker: PenTool,
  Spray: SprayCan,
  Pixel: Grid2X2,
  Reset: Monitor,
  FrameGrid: LayoutGrid,
  Monitor,
  LayoutGrid,
  Check,
  Mic,
  GripVertical,
  Wand2,
  Share2,
  Briefcase,
  ZoomIn,
  ZoomOut,
  Smartphone,
  Lasso,
  Scissors,
  Search,
  Camera,
  Bold,
  Italic,
  Brush,
  Video,
  Folder,
  FolderPlus,
  FolderOpen,
  FolderOutput,
  Film,
  Clapperboard,
  MoreVertical,
  Edit2,
  ArrowUpDown,
  ArrowUp,
  ArrowDown,
  Sun,
  Moon,
  Laptop,
  Box,
  Gamepad2,
  Code,
  Clock,
  BookOpen,
  Sparkles,
  Lightbulb,
  GraduationCap,
  Compass,
  Library,
  Wind,
  Zap,
  Filter,
  SlidersHorizontal,
  Sliders: SlidersHorizontal,
  Tag,
  Info,
  ExternalLink,
  Radio,
  Disc,
  Activity,
  Package,
  Flame,
  Coins,
  PlayCircle,
  PauseCircle,
  RefreshCw,
  ImagePlus,
  CheckSquare,
  Crop,
  Edit3
};
